#!/usr/bin/env bash
# Seed a local OpenFGA store with the rebac-primer model and policy tuples.
#
# This is the one-time setup that the in-process graph evaluator does from
# TypeScript fixtures. With OpenFGA the model and tuples live in the OpenFGA
# store instead.
#
# Prerequisites:
#   - OpenFGA running:  make openfga/up        (listens on $OPENFGA_API_URL)
#   - fga CLI:          brew install openfga/tap/fga
#   - jq:               brew install jq
#
# It writes the resulting store/model IDs to deployments/openfga/.ids.env, which
# the `make server-openfga` target sources so the app knows which store/model
# to talk to.
set -euo pipefail

API_URL="${OPENFGA_API_URL:-http://localhost:8080}"
DIR="$(cd "$(dirname "$0")" && pwd)"
MODEL_FILE="$DIR/model.fga"
IDS_FILE="$DIR/.ids.env"

for bin in fga jq; do
  command -v "$bin" >/dev/null 2>&1 || { echo "error: '$bin' is required (see prerequisites in this script)"; exit 1; }
done

echo "Creating store 'rebac-primer' on $API_URL ..."
STORE_ID=$(fga store create --name rebac-primer --api-url "$API_URL" | jq -r '.store.id')
echo "  store id: $STORE_ID"

echo "Writing authorization model from $MODEL_FILE ..."
MODEL_ID=$(fga model write --store-id "$STORE_ID" --api-url "$API_URL" --file "$MODEL_FILE" | jq -r '.authorization_model_id')
echo "  model id: $MODEL_ID"

echo "Seeding policy tuples (the workspace/team relationships) ..."
# fga tuple write takes:  <user> <relation> <object>
fga tuple write --store-id "$STORE_ID" --model-id "$MODEL_ID" --api-url "$API_URL" user:alice member team:platformTeam
fga tuple write --store-id "$STORE_ID" --model-id "$MODEL_ID" --api-url "$API_URL" team:platformTeam#member editor workspace:productWorkspace
fga tuple write --store-id "$STORE_ID" --model-id "$MODEL_ID" --api-url "$API_URL" user:bob viewer workspace:productWorkspace

cat > "$IDS_FILE" <<EOF
# Generated by deployments/openfga/seed.sh — sourced by make server-openfga.
OPENFGA_API_URL=$API_URL
OPENFGA_STORE_ID=$STORE_ID
OPENFGA_MODEL_ID=$MODEL_ID
EOF

echo
echo "Wrote $IDS_FILE:"
cat "$IDS_FILE"
echo
echo "Now run:  make server-openfga"
